name: "Test"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-linux-x86_64-extension:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable static
      #- run: pip install pytest numpy; make test-loadable
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-rembed-linux-x86_64-extension
          path: dist/*
  build-macos-x86_64-extension:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable static
      #- run: /usr/local/opt/python@3/libexec/bin/python -m pip install pytest numpy; make test-loadable python=/usr/local/opt/python@3/libexec/bin/python
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-rembed-macos-x86_64-extension
          path: dist/*
  build-macos-aarch64-extension:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable static
      #- run: /opt/homebrew/opt/python3/libexec/bin/python -m pip install pytest numpy --break-system-packages; make test-loadable python=/opt/homebrew/opt/python3/libexec/bin/python
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-rembed-macos-aarch64-extension
          path: dist/*
  build-windows-x86_64-extension:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable static
      #- run: pip install pytest numpy; make test-loadable
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-rembed-windows-x86_64-extension
          path: dist/*
